networks:
  default: localnet
  localnet:
    url: "http://127.0.0.1:4000/api"
    leader_only: false
  studionet: {}
  testnet_bradbury:
    accounts:
      - "${CREATOR_PRIVATE_KEY}"
      - "${KOL_PRIVATE_KEY}"
      - "${ATTACKER_PRIVATE_KEY}"
paths:
  contracts: "contracts"
  artifacts: "artifacts"
environment: .env
